env: production

nginx:
    image:
        registry: itsme-reg.kr.ncr.ntruss.com/nginx
        tag: latest
        pullPolicy: Always
    volumeMounts: ssl-config-dir
    resources:
        limits:
            cpu: 1
            memory: 1Gi

nodejs:
    image:
        registry: itsme-reg.kr.ncr.ntruss.com/covid-letter-web_app
        tag: latest
        pullPolicy: Always
    resources:
        limits:
            cpu: 1
            memory: 1Gi
    containerPort: 3000

hpa:
    minReplicas: 1
    maxReplicas: 2
