env: local

nginx:
    image:
        registry: workingnewjeong/nginx
        tag: latest
        pullPolicy: Always
    resources:
        limits:
            cpu: 1
            memory: 1Gi

nodejs:
    image:
        registry: workingnewjeong/covid-letter-web-dev_app
        tag: latest
        pullPolicy: Always
    resources:
        limits:
            cpu: 1
            memory: 1Gi
    containerPort: 3000

hpa:
    minReplicas: 1
    maxReplicas: 1
