version: '3'

services:
    nginx:
        image: nginx
        ports:
            - '80:80'
        volumes:
            - ./deployment/configs/nginx.conf:/etc/nginx/nginx.conf
            - ./deployment/configs/variable.conf:/etc/nginx/variable.conf
    app:
        build:
            context: .
            args:
                REACT_APP_ENV: local
