apiVersion: v1
data:
  nginx.conf: |-
    #user  nobody;
    worker_processes  auto;

    #error_log  logs/error.log;
    #error_log  logs/error.log  notice;
    #error_log  logs/error.log  info;

    #pid        logs/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       mime.types;
        include       variable.conf;
        default_type  text/html;

        # log
        log_format main '$remote_addr - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time';
        access_log access.log main;

        # gzip setting
        gzip on;
        gzip_disable "msie6";
        gzip_min_length 256;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/js
            text/xml
            text/javascript
            application/javascript
            application/x-javascript
            application/json
            application/xml
            application/rss+xml
            image/svg+xml;

        sendfile        on;
        #tcp_nopush     on;

        #keepalive_timeout  0;
        keepalive_timeout  65;

        proxy_cache_path /usr/share/nginx/cache levels=1:2 keys_zone=my_cache:10m max_size=1g;

        server {
            listen 80;
            server_name  _;

            location / {
                proxy_set_header HOST $host;
                proxy_pass http://node;
                proxy_http_version 1.1;
                proxy_redirect off;
            }

            location ~* \.(ico|css|gif|jpeg|jpg|png|woff|ttf|otf|svg|woff2|eot)$ {
                proxy_cache my_cache;
                proxy_ignore_headers Cache-Control;
                proxy_cache_valid 30d;
                proxy_pass http://node;
                # access_log off;
                # expires max;
                add_header X-Asset "yes";
                add_header access-control-allow-origin "*";
                # add_header Cache-Control "public";
            }

            location /_next/static {
                proxy_cache my_cache;
                proxy_pass http://node;
            }
        }

        # HTTPS server
        #
        #server {
        #    listen       443 ssl;
        #    server_name  localhost;

        #    ssl_certificate      cert.pem;
        #    ssl_certificate_key  cert.key;

        #    ssl_session_cache    shared:SSL:1m;
        #    ssl_session_timeout  5m;

        #    ssl_ciphers  HIGH:!aNULL:!MD5;
        #    ssl_prefer_server_ciphers  on;

        #    location / {
        #        root   html;
        #        index  index.html index.htm;
        #    }
        #}
        include servers/*;
    }
  variable.conf: |-
    upstream node {
        server localhost:3000;
    }
kind: ConfigMap
metadata:
  name: {{ include "covid-letter-web.fullname" . }}-configs
  labels:
    {{- include "covid-letter-web.labels" . | nindent 4 }}
