apiVersion: v1
kind: Service
metadata:
  name: {{ include "covid-letter-web.fullname" . }}
  labels: 
    {{- include "covid-letter-web.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  type: LoadBalancer
  selector: 
    {{- include "covid-letter-web.selectorLabels" . | nindent 4 }}
