name: Prettier & Lint Check

on:
  pull_request:
    branches: ['*']

jobs:
  check:
    name: Prettier & Lint Check
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier