name: Prettier & Lint Check

on:
  pull_request:
    branches: ['*']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - run: npm ci
      - run: npm run lint
      - uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check .