name: Unit Test

on:
  pull_request:
    branches: ['*']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - run: npm ci
      - run: npm run test:local